### PR TITLE
Improved support for mutable detection

### PR DESCRIPTION
**Pull request by VincentMasselis**
Added `MutableStateFlow` and `MutableSharedFlow`

Related to #62

### CODE REVIEW

**Comment by mrmans0n** [comment]
You'll need to write in a message "I have read the CLA Document and I hereby sign the CLA" for the CLA to pass.

**Review by mrmans0n — APPROVED** [review]

**Comment by VincentMasselis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by digitalbuddha** [comment]
Thank you for your contribution. ❤️

**Comment by VincentMasselis** [comment]
You're welcome

**Pull request merged**
